### ISSUE TITLE
Index Code is returning no values

### ISSUE THREAD

**Issue by sharu0071** [alloc7260/NSE#10]
Wile trying to run the Index code, it is giving the blanks in result. Can someone tells what is the problem ?

**Comment by sharu0071** [comment]
![Screenshot (20)](https://github.com/alloc7260/NSE/assets/111654959/6aeccf55-ee52-4697-96a2-92962bcde9c9)

**Comment by alloc7260** [comment]
@sharu0071  Thank you for your support, I have made changes in code.
Now you can pull the new code and try again.

**Comment by sharu0071** [comment]
The Code is again returning "NoneType" error while trying to use the code. Can you please check this?

**Comment by alloc7260** [comment]
@sharu0071 Fixed your issue
