### ISSUE TITLE
NIFTY index history possible ?

### ISSUE THREAD

**Issue by marc-odp** [alloc7260/NSE#4]
Hi. Thank you for providing this library. Works nicely.
I used to retrieve historical data using nsepy. However, I was not retrieving data of individual shares but for the global NIFTY index. Is that possible with your library ? I tried with the code NIFTY and NIFTY50 but got an error...
marc

**Comment by alloc7260** [comment]
@marc-odp 
Actually Nifty and Nifty50 is known as indexes and not a part of Stocks, They are like basket of stocks pre-configured in it.
Currently this lib is working for stocks only, and I am also looking forward to add indexes too. Sooner or later they become part of this.
Thank You

**Comment by alloc7260** [comment]
@marc-odp 
Your issue is resolved positively, you can now get index history data too.
Thanks for supporting.
