### ISSUE TITLE
Can we get NSE F&O data as well?

### ISSUE THREAD

**Issue by nbrengg** [alloc7260/NSE#5]
Hi Pranav,

Earlier given code is working fine. Can you please help to extract Future & Option data as well? Thanks.

**Comment by alloc7260** [comment]
@nbrengg 
Currently I am enrolled with a few projects, so not having much time for development of this lib. But I am looking forward to it whenever I am free. Sooner or later It will become part of this lib. 
Thank You

**Comment by sharu0071** [comment]
Can I use the Index to pull total return and P/E data also ?

**Comment by alloc7260** [comment]
@sharu0071 can you give me some examples so that I can be sure that what you are looking for.

**Comment by sharu0071** [comment]
Sure. In the Historical data page there is a drop down list right above the select an index type. In that list contains Historical Index Data, Archives of Daily/Monthly Reports, P/E & Div.Yields values and Total return Index Values.

**Comment by sharu0071** [comment]
I wanted the Total return Index Values of Nifty indices like Nifty 50, Nifty Next 50 etc. Similarly valuation ratios of Nifty 50, Nifty 100 Etc.

**Comment by alloc7260** [comment]
@sharu0071 please raise an another feature request for that. I will work on that after completing my TO DO.

**Comment by alloc7260** [comment]
@nbrengg 
Your issue is resolved positively, you can now get F&O data too.
Thanks for supporting.
